/**
 * paquete GUI
 */
package GUI;

import objNegocio.*;

/**
 * Clase BotonMenuSalir.java que implementa de la interfaz ISala.java.
 *
 * @author EQUIPO ARQUITECTURA INTEGRANTES: Jaime Sergio Efrain Jesus Ivan
 */
public class BotonMenuSalir extends javax.swing.JPanel implements ISala {

    /**
     * Instancias necesarias de la clase Jugador y SalaGUI.
     */
    private Jugador jgdr;
    private SalaGUI s;

    /**
     * Constructor que recibe como parámetro una instancia de tipo Jugador y
     * otra de SalaGUI y los inicializa con el valor de la clase.
     *
     * @param jgdr Instnacia Jugador.
     * @param s Instancia SalaGUI
     */
    public BotonMenuSalir(Jugador jgdr, SalaGUI s) {
        initComponents();
        this.jgdr = jgdr;
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSalir = new javax.swing.JButton();

        BtnSalir.setText("Abandonar partida");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método de tipo void el cual se encarga de volver al menu principal del
     * juego.
     *
     * @param evt Evento a realizar.
     */
    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        jgdr.setJgdrPuntos(0);
        MenuPrincipal mP = MenuPrincipal.getInstancia(jgdr);
        mP.setVisible(true);
    }//GEN-LAST:event_BtnSalirActionPerformed

    /**
     * Método de tipo void el cual actualiza la sala de juego.
     */
    @Override
    public void actualizaSala() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    // End of variables declaration//GEN-END:variables
}
