/**
 * Paquete GUI
 */
package GUI;

import objNegocio.*;
import java.awt.Color;
import java.awt.Dimension;

/**
 * Clase CuadroJugador.java
 *
 * @author EQUIPO ARQUITECTURA INTEGRANTES: Jaime Sergio Efrain Jesus Ivan
 */
public class CuadroJugador extends javax.swing.JPanel {

    /**
     * Instancia de la clase Jugador.
     */
    private Jugador jgdr;

    /**
     * Constructor de la clase el cual recibe como parámetro una instancia de la
     * clase Jugador. Mostrará en los labels la información correspondiente de
     * los jugadores.
     *
     * @param jgdr Instancia de la clase Jugador.
     */
    public CuadroJugador(Jugador jgdr) {
        initComponents();
        this.setSize(new Dimension(280, 80));
        this.jgdr = jgdr;
        this.labelNick.setText(this.jgdr.getJgdrNombre());
        this.labelPtj.setText(this.jgdr.getJgdrPuntos() + "");
        if (this.jgdr.getJgdrColor() != null) {
            this.setBackground(Color.decode(this.jgdr.getJgdrColor()));
        }
    }

    /**
     * Método de tipo void que recibe como parámetro una instancia de la clase
     * Jugador. Inicializa el valor de la instancia con el del parámetro.
     *
     * @param jgdr Instancia de la clase Jugador.
     */
    public void setJgdr(Jugador jgdr) {
        this.jgdr = jgdr;
    }

    /**
     * Método de tipo void que recibe como parámetro una atributo de tipo entero
     * el cual nos servirá para asignar el puntaje que lleva el jugador.
     *
     * @param puntaje Puntaje del jugador.
     */
    public void setPuntaje(int puntaje) {
        this.jgdr.setJgdrPuntos(puntaje);
        this.labelPtj.setText(puntaje + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAvt = new javax.swing.JLabel();
        labelPtj = new javax.swing.JLabel();
        labelNick = new javax.swing.JLabel();

        labelAvt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelAvt.setMaximumSize(new java.awt.Dimension(50, 50));
        labelAvt.setMinimumSize(new java.awt.Dimension(50, 50));
        labelAvt.setPreferredSize(new java.awt.Dimension(50, 50));

        labelPtj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPtj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPtj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPtj.setMaximumSize(new java.awt.Dimension(50, 50));
        labelPtj.setMinimumSize(new java.awt.Dimension(50, 50));
        labelPtj.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAvt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNick, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPtj, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNick, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPtj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAvt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAvt;
    private javax.swing.JLabel labelNick;
    private javax.swing.JLabel labelPtj;
    // End of variables declaration//GEN-END:variables
}
