/**
 * Paquete GUI
 */
package GUI;

import objNegocio.*;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 * Clase MenuPrincipal.java
 *
 * @author EQUIPO ARQUITECTURA INTEGRANTES: Jaime Sergio Efrain Jesus Ivan
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Definimos las instancias que utilizaremos. Necesitaremos una de la clase
     * Jugador y otra instancia estática de esta clase.
     */
    private Jugador jgdr;
    private static MenuPrincipal ins;

    /**
     * Constructor que recibe como parámetro una instancia de la clase Jugador.
     * Inicializamos el proyecto y nos manda al panel de registro.
     *
     * @param jgdr Instancia de la clase Jugador.
     */
    private MenuPrincipal(Jugador jgdr) {
        initComponents();
        this.setResizable(false);
        this.setPreferredSize(new Dimension(580, 370));
        this.setLocationRelativeTo(null);
        this.setTitle("Bienvenido al juego");

        if (jgdr == null) {
            RegistrarUsuario panelRegistro = new RegistrarUsuario(this, true);
            panelRegistro.setVisible(true);
        } else {
            this.jgdr = jgdr;
        }
    }

    /**
     * Método de tipo MenuPrincipal que recibe como parámetro una instancia de
     * la clase Jugador. El objetivo de este método es instanciar en esta misma
     * clase.
     *
     * @param jgdr Jugador.
     * @return Nos regresa la instancia de la clase Jugador.
     */
    public static MenuPrincipal getInstancia(Jugador jgdr) {
        if (ins == null) {
            ins = new MenuPrincipal(jgdr);
        }
        ins.setJgdr(jgdr);
        return ins;
    }

    /**
     * Método de tipo Jugador el cual nos regresa al jugador.
     *
     * @return Nos regresa al jugador.
     */
    public Jugador getJgdr() {
        return jgdr;
    }

    /**
     * Método de tipo void que recibe como parámetro una instancia de la clase
     * Jugador. Inicializa el valor de la instancia con el del parámetro y
     * asigna un nombre al jugador.
     *
     * @param jgdr
     */
    public void setJgdr(Jugador jgdr) {
        this.jgdr = jgdr;
        this.nombreJugador.setText(jgdr.getJgdrNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        unirPartida = new javax.swing.JButton();
        cerrarTimbiriche = new javax.swing.JButton();
        nombreJugador = new javax.swing.JLabel();
        crearSala = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unirPartida.setText("Unirse a una partida");
        unirPartida.setMaximumSize(new java.awt.Dimension(180, 180));
        unirPartida.setMinimumSize(new java.awt.Dimension(180, 180));
        unirPartida.setPreferredSize(new java.awt.Dimension(180, 180));
        unirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unirPartidaActionPerformed(evt);
            }
        });

        cerrarTimbiriche.setText("Cerrar");
        cerrarTimbiriche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarTimbiricheActionPerformed(evt);
            }
        });

        nombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        crearSala.setText("Crear partida");
        crearSala.setMaximumSize(new java.awt.Dimension(180, 180));
        crearSala.setMinimumSize(new java.awt.Dimension(180, 180));
        crearSala.setPreferredSize(new java.awt.Dimension(180, 180));
        crearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(crearSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unirPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cerrarTimbiriche, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unirPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearSala, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarTimbiriche)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Seleccione la opción que desea:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método de tipo void que sirve para poder unirse a cualquier partida.
     *
     * @param evt Evento a realizar.
     */
    private void unirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unirPartidaActionPerformed
        JOptionPane.showMessageDialog(this, "Un momento...", "Un momento por favor...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_unirPartidaActionPerformed

    /**
     * Método de tipo void el cual tiene como objetivo cancelar y salir.
     *
     * @param evt Evento a realizar.
     */
    private void cerrarTimbiricheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarTimbiricheActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cerrarTimbiricheActionPerformed

    /**
     * Método de tipo void el cual nos manda a la clase SalaRoomGUI para poder
     * seleccionar el número de jugadores que estarán en la partida.
     *
     * @param evt Evento a realizar.
     */
    private void crearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSalaActionPerformed
        SalaRoomGUI menuPrincipal = SalaRoomGUI.getInstancia(jgdr);
        this.dispose();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_crearSalaActionPerformed

    /**
     * Método main que corre todo en la clase.
     * 
     * @param args 
     */
    public static void main(String args[]) {
        /* Establece Look and Feel del sistema */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Crea y despliega MenuInicial*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarTimbiriche;
    private javax.swing.JButton crearSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JButton unirPartida;
    // End of variables declaration//GEN-END:variables
}
